#[derive(PartialEq, Debug)]
pub enum Token {
    TagPairStart(char),
    TagPairName(String),
    TagPairValue(String),
    TagPairEnd(char),
    TurnBegin(String),
    PieceMoving(char),
    MovingFrom(char),
    CaptureIndicator,
    MovingTo(String),
    CheckIndicator(char),
    CheckMateIndicator(char),
    PromotionStart(char),
    Promotion(char),
    PromotionEnd(char),
    AnnotationStart(char),
    Annotation(String),
    AnnotationEnd(char),
    MoveQuality(String),
    Nag(String),
    TurnContinuation(String),
    GameTermination(String),
    Unknown(String),
    NewLine,
}
