#[derive(PartialEq, Debug)]
pub enum Token {
    TagPairStart(char),
    TagPairName(String),
    TagPairValue(Option<String>),
    TagPairEnd(char),
    TurnBegin(String),
    PieceMoving(Option<char>),
    MovingFrom(Option<char>),
    CaptureIndicator,
    MovingTo(String),
    PromotionStart(char),
    Promotion(char),
    PromotionEnd(char),
    CheckIndicator(char),
    CheckMateIndicator(char),
    AnnotationStart(char),
    Annotation(String),
    AnnotationEnd(char),
    MoveQuality(String),
    Nag(String),
    TurnContinuation(String),
    GameTermination(String),
    Unknown(String),
    NewLine,
}
