use crate::board::board_position::BoardPosition;
use crate::board::position;
use crate::utils::custom_struct_iterator::CustomStructIterator;

#[derive(Default, Clone, Debug)]
pub struct GenericBoard<T> {
    a1: Option<T>,
    a2: Option<T>,
    a3: Option<T>,
    a4: Option<T>,
    a5: Option<T>,
    a6: Option<T>,
    a7: Option<T>,
    a8: Option<T>,

    b1: Option<T>,
    b2: Option<T>,
    b3: Option<T>,
    b4: Option<T>,
    b5: Option<T>,
    b6: Option<T>,
    b7: Option<T>,
    b8: Option<T>,

    c1: Option<T>,
    c2: Option<T>,
    c3: Option<T>,
    c4: Option<T>,
    c5: Option<T>,
    c6: Option<T>,
    c7: Option<T>,
    c8: Option<T>,

    d1: Option<T>,
    d2: Option<T>,
    d3: Option<T>,
    d4: Option<T>,
    d5: Option<T>,
    d6: Option<T>,
    d7: Option<T>,
    d8: Option<T>,

    e1: Option<T>,
    e2: Option<T>,
    e3: Option<T>,
    e4: Option<T>,
    e5: Option<T>,
    e6: Option<T>,
    e7: Option<T>,
    e8: Option<T>,

    f1: Option<T>,
    f2: Option<T>,
    f3: Option<T>,
    f4: Option<T>,
    f5: Option<T>,
    f6: Option<T>,
    f7: Option<T>,
    f8: Option<T>,

    g1: Option<T>,
    g2: Option<T>,
    g3: Option<T>,
    g4: Option<T>,
    g5: Option<T>,
    g6: Option<T>,
    g7: Option<T>,
    g8: Option<T>,

    h1: Option<T>,
    h2: Option<T>,
    h3: Option<T>,
    h4: Option<T>,
    h5: Option<T>,
    h6: Option<T>,
    h7: Option<T>,
    h8: Option<T>,
}

impl<T> GenericBoard<T> {
    pub const fn empty() -> Self {
        Self {
            a1: None,
            a2: None,
            a3: None,
            a4: None,
            a5: None,
            a6: None,
            a7: None,
            a8: None,
            b1: None,
            b2: None,
            b3: None,
            b4: None,
            b5: None,
            b6: None,
            b7: None,
            b8: None,
            c1: None,
            c2: None,
            c3: None,
            c4: None,
            c5: None,
            c6: None,
            c7: None,
            c8: None,
            d1: None,
            d2: None,
            d3: None,
            d4: None,
            d5: None,
            d6: None,
            d7: None,
            d8: None,
            e1: None,
            e2: None,
            e3: None,
            e4: None,
            e5: None,
            e6: None,
            e7: None,
            e8: None,
            f1: None,
            f2: None,
            f3: None,
            f4: None,
            f5: None,
            f6: None,
            f7: None,
            f8: None,
            g1: None,
            g2: None,
            g3: None,
            g4: None,
            g5: None,
            g6: None,
            g7: None,
            g8: None,
            h1: None,
            h2: None,
            h3: None,
            h4: None,
            h5: None,
            h6: None,
            h7: None,
            h8: None,
        }
    }
    pub const fn all(&self) -> [&Option<T>; 64] {
        [
            &self.a1, &self.b1, &self.c1, &self.d1, &self.e1, &self.f1, &self.g1, &self.h1,
            &self.a2, &self.b2, &self.c2, &self.d2, &self.e2, &self.f2, &self.g2, &self.h2,
            &self.a3, &self.b3, &self.c3, &self.d3, &self.e3, &self.f3, &self.g3, &self.h3,
            &self.a4, &self.b4, &self.c4, &self.d4, &self.e4, &self.f4, &self.g4, &self.h4,
            &self.a5, &self.b5, &self.c5, &self.d5, &self.e5, &self.f5, &self.g5, &self.h5,
            &self.a6, &self.b6, &self.c6, &self.d6, &self.e6, &self.f6, &self.g6, &self.h6,
            &self.a7, &self.b7, &self.c7, &self.d7, &self.e7, &self.f7, &self.g7, &self.h7,
            &self.a8, &self.b8, &self.c8, &self.d8, &self.e8, &self.f8, &self.g8, &self.h8,
        ]
    }
    pub const fn as_slice(&self) -> [[&Option<T>; 8]; 8] {
        [
            [&self.a1, &self.b1, &self.c1, &self.d1, &self.e1, &self.f1, &self.g1, &self.h1],
            [&self.a2, &self.b2, &self.c2, &self.d2, &self.e2, &self.f2, &self.g2, &self.h2],
            [&self.a3, &self.b3, &self.c3, &self.d3, &self.e3, &self.f3, &self.g3, &self.h3],
            [&self.a4, &self.b4, &self.c4, &self.d4, &self.e4, &self.f4, &self.g4, &self.h4],
            [&self.a5, &self.b5, &self.c5, &self.d5, &self.e5, &self.f5, &self.g5, &self.h5],
            [&self.a6, &self.b6, &self.c6, &self.d6, &self.e6, &self.f6, &self.g6, &self.h6],
            [&self.a7, &self.b7, &self.c7, &self.d7, &self.e7, &self.f7, &self.g7, &self.h7],
            [&self.a8, &self.b8, &self.c8, &self.d8, &self.e8, &self.f8, &self.g8, &self.h8],
        ]
    }
    pub const fn get(&self, board_position: BoardPosition) -> &Option<T> {
        match board_position {
            position::A1 => &self.a1,
            position::A2 => &self.a2,
            position::A3 => &self.a3,
            position::A4 => &self.a4,
            position::A5 => &self.a5,
            position::A6 => &self.a6,
            position::A7 => &self.a7,
            position::A8 => &self.a8,
            position::B1 => &self.b1,
            position::B2 => &self.b2,
            position::B3 => &self.b3,
            position::B4 => &self.b4,
            position::B5 => &self.b5,
            position::B6 => &self.b6,
            position::B7 => &self.b7,
            position::B8 => &self.b8,
            position::C1 => &self.c1,
            position::C2 => &self.c2,
            position::C3 => &self.c3,
            position::C4 => &self.c4,
            position::C5 => &self.c5,
            position::C6 => &self.c6,
            position::C7 => &self.c7,
            position::C8 => &self.c8,
            position::D1 => &self.d1,
            position::D2 => &self.d2,
            position::D3 => &self.d3,
            position::D4 => &self.d4,
            position::D5 => &self.d5,
            position::D6 => &self.d6,
            position::D7 => &self.d7,
            position::D8 => &self.d8,
            position::E1 => &self.e1,
            position::E2 => &self.e2,
            position::E3 => &self.e3,
            position::E4 => &self.e4,
            position::E5 => &self.e5,
            position::E6 => &self.e6,
            position::E7 => &self.e7,
            position::E8 => &self.e8,
            position::F1 => &self.f1,
            position::F2 => &self.f2,
            position::F3 => &self.f3,
            position::F4 => &self.f4,
            position::F5 => &self.f5,
            position::F6 => &self.f6,
            position::F7 => &self.f7,
            position::F8 => &self.f8,
            position::G1 => &self.g1,
            position::G2 => &self.g2,
            position::G3 => &self.g3,
            position::G4 => &self.g4,
            position::G5 => &self.g5,
            position::G6 => &self.g6,
            position::G7 => &self.g7,
            position::G8 => &self.g8,
            position::H1 => &self.h1,
            position::H2 => &self.h2,
            position::H3 => &self.h3,
            position::H4 => &self.h4,
            position::H5 => &self.h5,
            position::H6 => &self.h6,
            position::H7 => &self.h7,
            position::H8 => &self.h8,
        }
    }
    pub fn get_mut(&mut self, board_position: BoardPosition) -> &mut Option<T> {
        match board_position {
            position::A1 => &mut self.a1,
            position::A2 => &mut self.a2,
            position::A3 => &mut self.a3,
            position::A4 => &mut self.a4,
            position::A5 => &mut self.a5,
            position::A6 => &mut self.a6,
            position::A7 => &mut self.a7,
            position::A8 => &mut self.a8,
            position::B1 => &mut self.b1,
            position::B2 => &mut self.b2,
            position::B3 => &mut self.b3,
            position::B4 => &mut self.b4,
            position::B5 => &mut self.b5,
            position::B6 => &mut self.b6,
            position::B7 => &mut self.b7,
            position::B8 => &mut self.b8,
            position::C1 => &mut self.c1,
            position::C2 => &mut self.c2,
            position::C3 => &mut self.c3,
            position::C4 => &mut self.c4,
            position::C5 => &mut self.c5,
            position::C6 => &mut self.c6,
            position::C7 => &mut self.c7,
            position::C8 => &mut self.c8,
            position::D1 => &mut self.d1,
            position::D2 => &mut self.d2,
            position::D3 => &mut self.d3,
            position::D4 => &mut self.d4,
            position::D5 => &mut self.d5,
            position::D6 => &mut self.d6,
            position::D7 => &mut self.d7,
            position::D8 => &mut self.d8,
            position::E1 => &mut self.e1,
            position::E2 => &mut self.e2,
            position::E3 => &mut self.e3,
            position::E4 => &mut self.e4,
            position::E5 => &mut self.e5,
            position::E6 => &mut self.e6,
            position::E7 => &mut self.e7,
            position::E8 => &mut self.e8,
            position::F1 => &mut self.f1,
            position::F2 => &mut self.f2,
            position::F3 => &mut self.f3,
            position::F4 => &mut self.f4,
            position::F5 => &mut self.f5,
            position::F6 => &mut self.f6,
            position::F7 => &mut self.f7,
            position::F8 => &mut self.f8,
            position::G1 => &mut self.g1,
            position::G2 => &mut self.g2,
            position::G3 => &mut self.g3,
            position::G4 => &mut self.g4,
            position::G5 => &mut self.g5,
            position::G6 => &mut self.g6,
            position::G7 => &mut self.g7,
            position::G8 => &mut self.g8,
            position::H1 => &mut self.h1,
            position::H2 => &mut self.h2,
            position::H3 => &mut self.h3,
            position::H4 => &mut self.h4,
            position::H5 => &mut self.h5,
            position::H6 => &mut self.h6,
            position::H7 => &mut self.h7,
            position::H8 => &mut self.h8,
        }
    }
    pub const fn as_iter(&self) -> CustomStructIterator<GenericBoard<T>> {
        CustomStructIterator::from(self)
    }
    pub fn set(&mut self, board_position: BoardPosition, value_option: Option<T>) {
        self.replace(board_position, value_option);
    }
    pub fn replace(
        &mut self,
        board_position: BoardPosition,
        value_option: Option<T>,
    ) -> Option<T> {
        if let Some(value) = value_option {
            self.get_mut(board_position).replace(value)
        } else {
            self.get_mut(board_position).take()
        }
    }
}

impl<'a, T> Iterator for CustomStructIterator<'a, GenericBoard<T>> {
    type Item = (BoardPosition, &'a Option<T>);

    fn next(&mut self) -> Option<Self::Item> {
        let res = Some(match self.index {
            0 => (position::A1, &self.data.a1),
            1 => (position::A2, &self.data.a2),
            2 => (position::A3, &self.data.a3),
            3 => (position::A4, &self.data.a4),
            4 => (position::A5, &self.data.a5),
            5 => (position::A6, &self.data.a6),
            6 => (position::A7, &self.data.a7),
            7 => (position::A8, &self.data.a8),
            8 => (position::B1, &self.data.b1),
            9 => (position::B2, &self.data.b2),
            10 => (position::B3, &self.data.b3),
            11 => (position::B4, &self.data.b4),
            12 => (position::B5, &self.data.b5),
            13 => (position::B6, &self.data.b6),
            14 => (position::B7, &self.data.b7),
            15 => (position::B8, &self.data.b8),
            16 => (position::C1, &self.data.c1),
            17 => (position::C2, &self.data.c2),
            18 => (position::C3, &self.data.c3),
            19 => (position::C4, &self.data.c4),
            20 => (position::C5, &self.data.c5),
            21 => (position::C6, &self.data.c6),
            22 => (position::C7, &self.data.c7),
            23 => (position::C8, &self.data.c8),
            24 => (position::D1, &self.data.d1),
            25 => (position::D2, &self.data.d2),
            26 => (position::D3, &self.data.d3),
            27 => (position::D4, &self.data.d4),
            28 => (position::D5, &self.data.d5),
            29 => (position::D6, &self.data.d6),
            30 => (position::D7, &self.data.d7),
            31 => (position::D8, &self.data.d8),
            32 => (position::E1, &self.data.e1),
            33 => (position::E2, &self.data.e2),
            34 => (position::E3, &self.data.e3),
            35 => (position::E4, &self.data.e4),
            36 => (position::E5, &self.data.e5),
            37 => (position::E6, &self.data.e6),
            38 => (position::E7, &self.data.e7),
            39 => (position::E8, &self.data.e8),
            40 => (position::F1, &self.data.f1),
            41 => (position::F2, &self.data.f2),
            42 => (position::F3, &self.data.f3),
            43 => (position::F4, &self.data.f4),
            44 => (position::F5, &self.data.f5),
            45 => (position::F6, &self.data.f6),
            46 => (position::F7, &self.data.f7),
            47 => (position::F8, &self.data.f8),
            48 => (position::G1, &self.data.g1),
            49 => (position::G2, &self.data.g2),
            50 => (position::G3, &self.data.g3),
            51 => (position::G4, &self.data.g4),
            52 => (position::G5, &self.data.g5),
            53 => (position::G6, &self.data.g6),
            54 => (position::G7, &self.data.g7),
            55 => (position::G8, &self.data.g8),
            56 => (position::H1, &self.data.h1),
            57 => (position::H2, &self.data.h2),
            58 => (position::H3, &self.data.h3),
            59 => (position::H4, &self.data.h4),
            60 => (position::H5, &self.data.h5),
            61 => (position::H6, &self.data.h6),
            62 => (position::H7, &self.data.h7),
            63 => (position::H8, &self.data.h8),
            _ => return None,
        });
        self.index += 1;
        res
    }
}
